name: CI

on:
  pull_request:
  push:
    branches: main

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          cache: yarn
          node-version-file: .nvmrc
      - run: yarn install
      - run: yarn test
      - run: yarn build
      - run: yarn lint

  integration:
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v5
      - uses: ./
