name: Example

on:
  pull_request:
    types: [opened]

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/commenter@v1
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
